const PREFERENCE_LEVELS = {
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    LOW: 'LOW',
    UNAVAILABLE: 'UNAVAILABLE'
};

const PREFERENCE_WEIGHTS = {
    HIGH: 3,
    MEDIUM: 2,
    LOW: 1,
    UNAVAILABLE: 0
};

module.exports = {
    PREFERENCE_LEVELS,
    PREFERENCE_WEIGHTS
};